version: 2.1
orbs:
  android: circleci/android@2.1.2
jobs:
  snapshot:
    environment:
      # _JAVA_OPTIONS: "-Xmx1500m -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"
      TERM: 'dumb'
    executor:
      name: android/android-machine
      tag: 2021.10.1
      resource-class: large
    steps:
      - checkout
      - run:
          name: install retry
          command: scripts/install-retry.sh
      - run:
          name: build
          command: |
            yes | sdkmanager "platforms;android-30" || true
            /tmp/retry -m 3 ./gradlew :android:assembleRelease --info
      - run:
          name: deploy snapshot
          command: |
            /tmp/retry -m 3 scripts/publish-android-snapshot.sh
      - android/save-gradle-cache:
          cache-prefix: v1a
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - snapshot
#           filters:
#             branches:
#               only: main
